apiVersion: apps.openshift.io/v1
kind: "DeploymentConfig"
metadata:
  name: spring
spec:
  template:
    metadata:
      labels:
        name: spring
    spec:
      containers:
        - name: spring
          image: "docker-registry.default.svc:5000/kuboot/spring@sha256:7aebcb59b113a0baf2aeddcd780170fc559284644448cdb5e3097dc21b0affc8"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
  selector:
    name: spring
  strategy:
    type: "Rolling"
