apiVersion: apps.openshift.io/v1
kind: "DeploymentConfig"
metadata:
  name: spring
spec:
  template:
    metadata:
      labels:
        name: spring
    spec:
      containers:
        - name: "helloworld"
          image: "docker-registry.default.svc:5000/kuboot/spring@sha256:2d7a3e4309ddd8a91e0df967367a8ca3ec131688b3d008025122aae8ecba14d9"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  selector:
    name: spring
  strategy:
    type: "Rolling"
