server:
  port: 8080
logging:
  level:
    root: debug
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/kuboot?useUnicode=true&amp&characterEncoding=utf-8
    username: kuboot
    password: kubootdb
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: spring.ku.boot.model

STORAGE_PATH: /Users/shaofeiliu/images/