server:
  port: 8080
  error:
    whitelabel:
      enabled: false
logging:
  level:
    root: debug
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luna?useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: none
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: spring.ku.boot.model
envName: basic2
security:
  basic:
    enabled: false