server:
  port: 8080
  error:
    whitelabel:
      enabled: false
logging:
  level:
    root: debug
spring:
  session:
    store-type: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db/luna?useUnicode=true&amp&characterEncoding=utf-8
    username: wordpress
    password: wordpress
  redis:
    host: redis
    port: 6379
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: spring.ku.boot.model
envName: basic2
security:
  basic:
    enabled: false