server:
  port: 8080
  error:
    whitelabel:
      enabled: false
logging:
  level:
    root: debug
spring:
  session:
    store-type: REDIS
    redis:
      flush-mode: on-save
      namespace: afsession
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://db/luna?useUnicode=true&amp&characterEncoding=utf-8
    username: wordpress
    password: wordpress
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: spring.ku.boot.model
envName: basic2